fastlane_version "2.62.1"

fastlane_require 'dotenv'
Dotenv.load '.env.secret'

default_platform(:android)
skip_docs # Do not create fastlane/README.md

def escape_markdown(str)
  str.gsub(/([_*\[`])/, '\\\\\1')
end

def truncate(string, max)
  string.length > max ? "#{string[0...max]}\n..." : string
end

platform :android do
  # ... before_all и другие лэйны без изменений ...

  desc "Composit task (clean, increment, build, commit) for local/CI build without Play Store"
  lane :bundleRelease do |options|
    versionCode = increment_version_code(
      gradle_file_path: "app_manager/appmanager/build.gradle.kts"
    )

    versionName = android_get_version_name(
      gradle_file: "app_manager/appmanager/build.gradle.kts"
    )

    # Read changelog
    changelog = ""
    change_log_file = options[:changelog_file]
    if File.exist?(change_log_file)
      changelog = File.read(change_log_file)
    else
      changelog = changelog_from_git_commits(
        pretty: "- %s",
        date_format: "short",
        match_lightweight_tag: false,
        merge_commit_filtering: "exclude_merges"
      )
    end

    telegram_changelog = truncate(escape_markdown(changelog), 3500)

    # Cleanup and build
    cleanup

    gradle(
      task: 'bundle',
      build_type: 'Release',
      project_dir: 'app_manager/',
    )

    git_version_bumped

    # Optional: notify in Telegram
    begin
      telegram(
        token: ENV['TELEGRAM_BOT_TOKEN'],
        chat_id: ENV['TELEGRAM_CHAT_ID'],
        parse_mode: 'Markdown',
        text: ENV["TELEGRAM_DOCUMENTS_ANDROID_MESSAGE"] % {
          versionName: versionName,
          versionCode: versionCode,
          changelog: telegram_changelog
        }
      )
    rescue => ex
      UI.error(ex)
    end

    sleep(5)
  end

  desc "Task for CI: build bundle and bump version, without Play Store"
  lane :publish_market_and_apk do |options|
    cleanup
    increment_build
    gradle(
      task: 'bundle',
      build_type: 'Release',
      project_dir: 'app_manager/',
    )
    git_version_bumped
  end

  desc "Build the application as APK files for all platforms"
  lane :apk do |options|
    # Build
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: 'app_manager/',
    )
  end

  desc "Upload a new build to Google Play"
  lane :upload_to_play_store_bundle do |options|
    upload_to_play_store(
      track: options[:track] || 'internal', # Default to 'internal' track
      aab: 'app_manager/appmanager/build/outputs/bundle/release/appmanager-release.aab'
    )
  end


  desc "Upload metadata to Google Play Store"
  lane :upload_metadata do |options|
     production_version_codes = google_play_track_version_codes(
       track: 'production'
     )

    latest_production_version = production_version_codes.max

    UI.message("Using production version code: #{latest_production_version}")
    upload_to_play_store(
      track: 'production',
      skip_upload_aab: true,
      skip_upload_apk: true,
      metadata_path: options[:metadata_path] || '../mobile-store/documents-playmarket/metadata',
      version_code: latest_production_version
    )

    UI.success("Metadata uploaded successfully")
  end

    desc "Runs all the tests"
        lane :test do
            gradle(task: "test", project_dir: 'app_manager/')
    end

end

